music: music.cpp songs.txt 
	g++ -g music.cpp -o music
see:
	vim music.cpp
run: music
	./music
seev:
	vim makefile
seef:
	vim songs.txt
fix:
	cp songsbackup.txt songs.txt
backup:
	cp music.cpp musicbackup.cpp
